name: "Build and release"

on:
  workflow_dispatch:
  push:
    branches:
      - development
      - 1.8 # increment for each major build

jobs:
  latest-release:
    name: "Latest Release"
    runs-on: "macos-latest"

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set release flags based on branch
        run: |
          echo "X_SHORT_HASH=`git rev-parse --short HEAD`" >> $GITHUB_ENV
          echo "X_RELEASE_TAG=${{ github.ref_name == 'development' && 'preview' || startsWith(github.ref_name, '1.') && 'stable' || github.ref_name }}" >> $GITHUB_ENV
          grep -Eo 'version.*\.\d+' src/manifest/manifest-chrome.json > ver.tmp
          sed -E 's/[^0-9]*([0-9.]+).*/X_VERSION=\1/' ver.tmp >> $GITHUB_ENV
          sed -E 's/[^0-9]*([0-9]+\.[0-9]+(\.[1-9][0-9]*)?).*/X_SAFARI_VERSION=\1/' ver.tmp >> $GITHUB_ENV
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Download WikiTree+ templates
        # only run this once per release to ensure it is identical in all builds
        run: npm run download-templates
      - name: Build for Chrome
        run: |
          npm run clean
          npm run build
          cd dist
          zip -r ../dist-chrome.zip *
          cd ..
      - name: Prepare Xcode environment
        env:
          X_SAFARI_FOLDER: ${{ env.X_RELEASE_TAG == 'stable' && 'WikiTree Browser Extension' || 'WikiTree Browser Extension (Preview)' }}
          X_SAFARI_PROJECT: xcode/${{ env.X_RELEASE_TAG == 'stable' && 'WikiTree Browser Extension' || 'WikiTree Browser Extension (Preview)' }}/${{ env.X_RELEASE_TAG == 'stable' && 'WikiTree Browser Extension' || 'WikiTree Browser Extension (Preview)' }}.xcodeproj
        run: |
          echo "X_SAFARI_FOLDER=${{ env.X_SAFARI_FOLDER }}" >> $GITHUB_ENV
          echo "X_SAFARI_PROJECT=${{ env.X_SAFARI_PROJECT }}" >> $GITHUB_ENV
          echo "X_SAFARI_CAN_SIGN=${{ secrets.BUILD_CERTIFICATE_BASE64 != '' && 'true' || 'false' }}" >> $GITHUB_ENV
          mv -f "${{ env.X_SAFARI_PROJECT }}/project.pbxproj" "${{ env.X_SAFARI_PROJECT }}/project.pbxproj.tmp"
          sed -E 's/MARKETING_VERSION[ ]*=[ ]*[0-9.]+/MARKETING_VERSION = ${{ env.X_SAFARI_VERSION }}/Ig' "${{ env.X_SAFARI_PROJECT }}/project.pbxproj.tmp" > "${{ env.X_SAFARI_PROJECT }}/project.pbxproj"
      - name: Install the Apple certificate and provisioning profile
        if: env.X_SAFARI_CAN_SIGN == 'true'
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      - name: Build for Safari (iOS)
        if: env.X_SAFARI_CAN_SIGN == 'true'
        # using dist already built from Chrome
        run: |
          rm -rf xcode/*.xcarchive
          xcodebuild clean archive -quiet -project "${{ env.X_SAFARI_PROJECT }}" -scheme "${{ env.X_SAFARI_FOLDER }} (iOS)" -configuration Release -destination generic/platform=iOS -allowProvisioningUpdates -archivePath xcode/output
          cd xcode/output.xcarchive/Products/Applications
          zip -r ../../../../dist-safari-ios.zip "${{ env.X_SAFARI_FOLDER }}.app"
          cd ../../../..
      - name: Build for Safari (macOS)
        run: |
          mv -f "${{ env.X_SAFARI_PROJECT }}/project.pbxproj" "${{ env.X_SAFARI_PROJECT }}/project.pbxproj.tmp"
          sed -E 's/(DEVELOPMENT_TEAM[ ]*=[ ]*.*;)/\/* \1 *\//Ig' "${{ env.X_SAFARI_PROJECT }}/project.pbxproj.tmp" > "${{ env.X_SAFARI_PROJECT }}/project.pbxproj"
          rm -rf xcode/*.xcarchive
          xcodebuild clean archive -quiet -project "${{ env.X_SAFARI_PROJECT }}" -scheme "${{ env.X_SAFARI_FOLDER }} (macOS)" -configuration Release -destination generic/platform=macOS -archivePath xcode/output
          cd xcode/output.xcarchive/Products/Applications
          zip -r ../../../../dist-safari-macos.zip "${{ env.X_SAFARI_FOLDER }}.app"
          cd ../../../..
      - name: Build for Firefox
        run: |
          npm run clean
          npm run build-firefox
          cd dist
          zip -r ../dist-firefox.zip *
          cd ..
      - name: Rename release assets
        run: |
          mv dist-chrome.zip wbe-${{ env.X_RELEASE_TAG }}-${{ env.X_VERSION }}-${{ env.X_SHORT_HASH }}-chrome.zip
          mv dist-firefox.zip wbe-${{ env.X_RELEASE_TAG }}-${{ env.X_VERSION }}-${{ env.X_SHORT_HASH }}-firefox.zip
          mv dist-safari-macos.zip wbe-${{ env.X_RELEASE_TAG }}-${{ env.X_VERSION }}-${{ env.X_SHORT_HASH }}-safari-macos.zip
          [ ! -f dist-safari-ios.zip ] || mv dist-safari-ios.zip wbe-${{ env.X_RELEASE_TAG }}-${{ env.X_VERSION }}-${{ env.X_SHORT_HASH }}-safari-ios.zip
      - name: Update release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: ${{ env.X_RELEASE_TAG != 'stable' }}
          files: wbe-*.zip
          automatic_release_tag: "${{ (env.X_RELEASE_TAG == 'stable' || env.X_RELEASE_TAG == 'preview') && env.X_RELEASE_TAG || format('release-{0}', github.ref_name) }}"
          title: ${{ env.X_RELEASE_TAG }}-${{ env.X_VERSION }}
